name: Build Docker Image and Run Tests

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - 'dockers/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./dockers
        file: ./dockers/Dockerfile
        tags: test-image:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max